---
- hosts: rhel7
  tasks:
    - name: Add Artifactory repos
      yum_repository:
        baseurl: "{{ item.baseurl }}"
        description: "{{ item.description }}"
        gpgcheck: "{{ item.gpgcheck }}"
        name: "{{ item.name }}"
      loop:
        - baseurl: "https://{{ lookup('env', 'ARTIFACTORY_USERNAME') }}:{{ lookup('env', 'ARTIFACTORY_PASSWORD') }}@artifactory.corp.mongodb.com/artifactory/rpm/7.8.2003/os/x86_64"  # noqa 204
          description: Artifactory RHEL 7 OS Packages
          gpgcheck: false
          name: rhel7os
        - baseurl: "https://{{ lookup('env', 'ARTIFACTORY_USERNAME') }}:{{ lookup('env', 'ARTIFACTORY_PASSWORD') }}@artifactory.corp.mongodb.com/artifactory/rpm/7.8.2003/extras/x86_64"  # noqa 204
          description: Artifactory RHEL 7 Extra Packages
          gpgcheck: false
          name: rhel7extra

- hosts: rhel8
  tasks:
    - name: Add Artifactory repos
      yum_repository:
        baseurl: "{{ item.baseurl }}"
        description: "{{ item.description }}"
        gpgcheck: "{{ item.gpgcheck }}"
        name: "{{ item.name }}"
      loop:
        - baseurl: "https://{{ lookup('env', 'ARTIFACTORY_USERNAME') }}:{{ lookup('env', 'ARTIFACTORY_PASSWORD') }}@artifactory.corp.mongodb.com/artifactory/rpm/8/AppStream/x86_64/os"  # noqa 204
          description: Artifactory RHEL 8 AppStream Packages
          gpgcheck: false
          name: rhel8appstream
        - baseurl: "https://{{ lookup('env', 'ARTIFACTORY_USERNAME') }}:{{ lookup('env', 'ARTIFACTORY_PASSWORD') }}@artifactory.corp.mongodb.com/artifactory/rpm/8/BaseOS/x86_64/os"  # noqa 204
          description: Artifactory RHEL 8 BaseOS Packages
          gpgcheck: false
          name: rhel8baseos

- hosts: debian10,ubuntu1804,ubuntu2004
  tasks:
    - name: Download prerequisites
      apt:
        name: "{{ item }}"
      loop:
        - python3-apt
        - python3-distutils

- hosts: all
  tasks:
    - name: Download python3
      package:
        name: python3
